/* MakeMyBrand API Playground — zero dependencies, no build step.
 *
 * Reads playground/spec.json (generated by postman/generate.js) and turns it into a
 * clickable client. The spec is a Postman v2.1 collection, so each request already
 * carries its body, query params, docs and the little script that captures ids for the
 * next call. We run a deliberately tiny subset of the Postman script API — see makePm.
 */

const STORE_KEY = 'mmb-pg-env';

const state = {
  collection: null,
  seedEnv: {},          // pristine values from the spec, for "reset"
  env: {},              // live values, persisted to localStorage
  item: null,           // request currently open
  edits: new Map(),     // per-request unsaved edits, keyed by path; session only
};

// ── helpers ────────────────────────────────────────────────────────────────
const $  = (sel) => document.querySelector(sel);
const el = (tag, cls, text) => {
  const node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;
  return node;
};

// Postman's built-in dynamic variables, reimplemented so a collection written against
// them behaves the same here. Used for fields under a unique constraint, where a
// hardcoded sample value collides the second time anyone runs the request.
const DYNAMIC = {
  $timestamp: () => String(Math.floor(Date.now() / 1000)),
  $randomInt: () => String(Math.floor(Math.random() * 1000)),
  $guid: () => (crypto.randomUUID ? crypto.randomUUID() : String(Date.now())),
};

/** Replace {{var}} from the environment, reporting any that resolve to nothing. */
function interpolate(str) {
  const missing = [];
  const out = String(str ?? '').replace(/\{\{(\$?\w+)\}\}/g, (_, name) => {
    if (DYNAMIC[name]) return DYNAMIC[name]();
    const value = state.env[name];
    if (value === undefined || value === '') { missing.push(name); return `{{${name}}}`; }
    return value;
  });
  return { out, missing };
}

function setVar(name, value) {
  state.env[name] = value == null ? '' : String(value);
  persistEnv();
  renderVars();
  renderAuthState();
}

function persistEnv() {
  try { localStorage.setItem(STORE_KEY, JSON.stringify(state.env)); } catch { /* private mode */ }
}

// ── the Postman script shim ────────────────────────────────────────────────
// Across all 88 requests the scripts touch exactly six things: pm.environment.set,
// pm.response.json, pm.response.code, pm.response.headers.get, pm.test and pm.expect.
// That is the whole contract, so this stays small on purpose.
function makePm(ctx) {
  const expect = (actual) => ({
    to: {
      be: {
        within(min, max) {
          if (!(actual >= min && actual <= max)) throw new Error(`expected ${actual} to be ${min}–${max}`);
        },
      },
      have: {
        property(key) {
          if (!actual || !Object.prototype.hasOwnProperty.call(actual, key)) {
            throw new Error(`expected a "${key}" property`);
          }
        },
      },
    },
  });

  return {
    environment: {
      set: (key, value) => { setVar(key, value); ctx.captured.push([key, String(value ?? '')]); },
      get: (key) => state.env[key],
      unset: (key) => setVar(key, ''),
    },
    response: {
      json: () => {
        if (ctx.json === undefined) throw new Error('response is not JSON');
        return ctx.json;
      },
      code: ctx.status,
      text: () => ctx.text,
      headers: { get: (key) => ctx.headers[String(key).toLowerCase()] },
    },
    test: (name, fn) => {
      try { fn(); ctx.tests.push({ name, ok: true }); }
      catch (err) { ctx.tests.push({ name, ok: false, error: err.message }); }
    },
    expect,
    variables: { get: (key) => state.env[key] },
  };
}

function runScript(lines, ctx) {
  if (!lines || !lines.length) return;
  try {
    // eslint-disable-next-line no-new-func
    new Function('pm', 'console', lines.join('\n'))(makePm(ctx), { log() {}, warn() {}, error() {} });
  } catch (err) {
    ctx.scriptError = err.message;
  }
}

const scriptOf = (item, listen) =>
  ((item.event || []).find((e) => e.listen === listen) || {}).script?.exec || [];

// ── request assembly ───────────────────────────────────────────────────────
function itemKey(item) { return item.__path.join('/'); }

function editsFor(item) {
  const key = itemKey(item);
  if (!state.edits.has(key)) {
    const req = item.request;
    state.edits.set(key, {
      body: req.body?.mode === 'raw' ? req.body.raw : null,
      query: (req.url.query || []).map((q) => ({ ...q })),
    });
  }
  return state.edits.get(key);
}

function buildUrl(item) {
  const edit = editsFor(item);
  const base = interpolate((item.request.url.host || ['{{base_url}}']).join(''));
  const segs = (item.request.url.path || []).map((s) => interpolate(s));
  const missing = [...base.missing, ...segs.flatMap((s) => s.missing)];

  let url = base.out.replace(/\/$/, '');
  if (segs.length) url += '/' + segs.map((s) => s.out).join('/');

  const pairs = [];
  for (const q of edit.query) {
    if (q.disabled) continue;
    const v = interpolate(q.value);
    missing.push(...v.missing);
    pairs.push(`${encodeURIComponent(q.key)}=${encodeURIComponent(v.out)}`);
  }
  if (pairs.length) url += '?' + pairs.join('&');

  return { url, missing: [...new Set(missing)] };
}

function authHeaderFor(item) {
  // A request's own auth overrides the collection default (noauth on public routes).
  const auth = item.request.auth || state.collection.auth;
  if (!auth || auth.type === 'noauth') return null;
  if (auth.type === 'bearer') {
    const token = interpolate((auth.bearer || [])[0]?.value || '');
    return token.missing.length ? null : `Bearer ${token.out}`;
  }
  return null;
}

/** Variables this request would send unresolved, across both the URL and the body. */
function missingFor(item) {
  const edit = editsFor(item);
  const out = [...buildUrl(item).missing];
  const method = item.request.method;
  if (edit.body != null && method !== 'GET' && method !== 'HEAD') {
    out.push(...interpolate(edit.body).missing);
  }
  return [...new Set(out)];
}

async function sendRequest(item) {
  const built = buildUrl(item);
  const url = built.url;
  const missing = missingFor(item);
  const edit = editsFor(item);
  const method = item.request.method;

  const headers = {};
  const auth = authHeaderFor(item);
  if (auth) headers.Authorization = auth;

  let body;
  if (edit.body != null && method !== 'GET' && method !== 'HEAD') {
    body = interpolate(edit.body).out;
    headers['Content-Type'] = 'application/json';
  }

  const started = performance.now();
  let res, text = '', networkError = null;
  try {
    res = await fetch(url, { method, headers, body });
    text = await res.text();
  } catch (err) {
    networkError = err.message;
  }
  const ms = Math.round(performance.now() - started);

  const ctx = {
    url, method, ms, networkError,
    missing: [...new Set(missing)],
    status: res ? res.status : 0,
    statusText: res ? res.statusText : '',
    headers: res ? Object.fromEntries([...res.headers].map(([k, v]) => [k.toLowerCase(), v])) : {},
    text,
    json: undefined,
    tests: [],
    captured: [],
    scriptError: null,
  };
  try { ctx.json = JSON.parse(text); } catch { /* not JSON — leave undefined */ }

  if (!networkError) runScript(scriptOf(item, 'test'), ctx);
  return ctx;
}

// ── rendering: sidebar ─────────────────────────────────────────────────────
function renderTree(filterText = '') {
  const tree = $('#tree');
  tree.textContent = '';
  const needle = filterText.trim().toLowerCase();

  for (const folder of state.collection.item) {
    const requests = [];
    (function walk(items, trail) {
      for (const it of items) {
        if (it.item) walk(it.item, trail.concat(it.name));
        else { it.__path = trail.concat(it.name); requests.push(it); }
      }
    })(folder.item || [], [folder.name]);

    const shown = needle
      ? requests.filter((r) => r.name.toLowerCase().includes(needle)
          || r.request.url.path.join('/').toLowerCase().includes(needle))
      : requests;
    if (!shown.length) continue;

    const group = el('div', 'group');
    const head = el('div', 'group-head');
    const title = el('button', 'group-title');
    title.append(el('span', 'caret', '▾'), el('span', null, folder.name), el('span', 'count', String(shown.length)));
    const run = el('button', 'run-folder', 'Run folder');
    run.title = `Send all ${shown.length} requests in order, stopping at the first failure`;
    run.onclick = (e) => { e.stopPropagation(); runFolder(folder.name, shown); };
    head.append(title, run);

    const list = el('div', 'group-items');
    for (const req of shown) {
      const row = el('button', 'req-row');
      row.append(el('span', `m m-${req.request.method}`, req.request.method), el('span', 'rn', req.name));
      row.onclick = () => openRequest(req);
      row.dataset.key = itemKey(req);
      list.append(row);
    }
    title.onclick = () => { group.classList.toggle('collapsed'); };
    group.append(head, list);
    if (needle) group.classList.remove('collapsed');
    tree.append(group);
  }
}

function markActive(item) {
  document.querySelectorAll('.req-row').forEach((r) => r.classList.remove('active'));
  const row = document.querySelector(`.req-row[data-key="${CSS.escape(itemKey(item))}"]`);
  if (row) row.classList.add('active');
}

// ── rendering: request pane ────────────────────────────────────────────────
function openRequest(item) {
  state.item = item;
  markActive(item);
  $('#empty').classList.add('hidden');
  $('#run-pane').classList.add('hidden');
  $('#request-pane').classList.remove('hidden');

  $('#req-name').textContent = item.name;
  $('#req-method').textContent = item.request.method;
  $('#req-method').className = `method m-${item.request.method}`;
  $('#req-desc').innerHTML = mdLite(item.request.description || '');
  $('#req-desc').classList.toggle('hidden', !item.request.description);

  renderUrlLine();
  renderParams();

  const edit = editsFor(item);
  const bodyTab = [...$('#req-tabs').children].find((b) => b.dataset.tab === 'body');
  bodyTab.classList.toggle('hidden', edit.body == null);
  $('#body-editor').value = edit.body ?? '';
  $('#body-hint').textContent = edit.body == null ? '' : 'Values in {{braces}} are substituted from the Variables panel when you send.';

  const captures = scriptOf(item, 'test')
    .filter((l) => l.includes('environment.set'))
    .map((l) => l.trim());
  $('#script-view').textContent = captures.length ? captures.join('\n') : 'This request captures nothing.';

  selectTab(edit.body != null ? 'body' : 'params');
  $('#response').textContent = '';
}

function renderUrlLine() {
  const { url, missing } = buildUrl(state.item);
  const code = $('#req-url');
  code.textContent = url;
  code.classList.toggle('has-missing', missing.length > 0);
  code.title = missing.length ? `Unset variable(s): ${missing.join(', ')}` : url;
}

function renderParams() {
  const host = $('#tab-params');
  host.textContent = '';
  const edit = editsFor(state.item);

  if (!edit.query.length) {
    host.append(el('p', 'hint', 'This request takes no query parameters.'));
    return;
  }
  const table = el('table', 'params');
  for (const q of edit.query) {
    const tr = el('tr');
    const box = el('input');
    box.type = 'checkbox';
    box.checked = !q.disabled;
    box.onchange = () => { q.disabled = !box.checked; renderUrlLine(); };

    const val = el('input', 'val');
    val.type = 'text';
    val.value = q.value;
    val.spellcheck = false;
    val.oninput = () => { q.value = val.value; renderUrlLine(); };

    tr.append(el('td', 'chk'), el('td', 'key', q.key), el('td', 'v'));
    tr.children[0].append(box);
    tr.children[2].append(val);
    table.append(tr);
  }
  host.append(table);
}

function selectTab(name) {
  for (const btn of $('#req-tabs').children) btn.classList.toggle('active', btn.dataset.tab === name);
  for (const id of ['params', 'body', 'script']) $(`#tab-${id}`).classList.toggle('hidden', id !== name);
}

// ── rendering: response ────────────────────────────────────────────────────
function responseCard(ctx) {
  const card = el('div', 'response');

  if (ctx.networkError) {
    card.append(el('div', 'status-line fail', `Request failed — ${ctx.networkError}`));
    card.append(el('p', 'hint', 'The server may be down, or the browser blocked this by CORS if the base URL points somewhere else.'));
    return card;
  }

  const ok = ctx.status >= 200 && ctx.status < 300;
  const line = el('div', `status-line ${ok ? 'ok' : 'fail'}`);
  line.append(
    el('span', 'code', `${ctx.status} ${ctx.statusText}`),
    el('span', 'muted', `${ctx.ms} ms`),
    el('span', 'muted', `${ctx.text.length} B`),
  );
  card.append(line);

  if (ctx.missing.length) {
    card.append(el('div', 'warn', `Sent with unresolved variable(s): ${ctx.missing.join(', ')} — run the request that fills them first.`));
  }

  // Envelope-aware: the API always answers { success, data, meta? } or
  // { success:false, error:{ code, message, details } }.
  const body = ctx.json;
  if (body && body.success === false && body.error) {
    const box = el('div', 'error-box');
    box.append(el('div', 'err-code', body.error.code || 'ERROR'));
    box.append(el('div', 'err-msg', body.error.message || ''));
    const details = body.error.details;
    if (Array.isArray(details) && details.length) {
      const dl = el('table', 'details');
      for (const d of details) {
        const tr = el('tr');
        tr.append(el('td', 'f', d.field || ''), el('td', null, d.message || JSON.stringify(d)));
        dl.append(tr);
      }
      box.append(dl);
    }
    card.append(box);
  }

  if (ctx.captured.length) {
    const cap = el('div', 'captured');
    cap.append(el('span', 'cap-label', 'Captured'));
    for (const [k, v] of ctx.captured) {
      cap.append(el('span', 'chip', `${k} = ${v.length > 22 ? v.slice(0, 22) + '…' : v}`));
    }
    card.append(cap);
  }

  if (ctx.tests.length) {
    const row = el('div', 'tests');
    for (const t of ctx.tests) row.append(el('span', `chip ${t.ok ? 'pass' : 'fail'}`, t.name));
    card.append(row);
  }
  if (ctx.scriptError) card.append(el('div', 'warn', `Capture script error: ${ctx.scriptError}`));

  const pre = el('pre', 'json');
  pre.textContent = body !== undefined ? JSON.stringify(body, null, 2) : (ctx.text || '(empty response)');
  card.append(pre);
  return card;
}

// ── flow mode ──────────────────────────────────────────────────────────────
// Requests that end the session — or the account. Run mid-folder they'd 401 every step
// after them, and Deactivate would take the shared test user down with it. Flow mode
// skips them and says so; they still run normally when opened on their own.
const SESSION_DESTRUCTIVE = ['auth/logout', 'users/me/deactivate'];
const isDestructive = (item) => SESSION_DESTRUCTIVE.includes((item.request.url.path || []).join('/'));

async function runFolder(name, requests) {
  state.item = null;
  $('#empty').classList.add('hidden');
  $('#request-pane').classList.add('hidden');
  const pane = $('#run-pane');
  pane.classList.remove('hidden');
  pane.textContent = '';

  pane.append(el('h2', null, `Run folder — ${name}`));
  pane.append(el('p', 'hint', 'Requests run in order and stop at the first non-2xx, so the first red row is where the journey actually breaks.'));
  const log = el('div', 'runlog');
  pane.append(log);

  let failed = null;
  let skipped = 0;
  for (const req of requests) {
    const row = el('div', 'run-row');
    const head = el('div', 'run-head');
    head.append(
      el('span', `m m-${req.request.method}`, req.request.method),
      el('span', 'rn', req.name),
      el('span', 'run-status', '…'),
    );
    row.append(head);
    log.append(row);
    row.scrollIntoView({ block: 'nearest' });

    const skipReason = isDestructive(req)
      ? 'Ends your session — open it on its own to run it.'
      : (() => {
          // A request carrying an unresolved {{var}} is already known to fail, and the
          // server's complaint would be about the literal braces rather than the real
          // problem. Naming the missing variable is the more useful answer.
          const unresolved = missingFor(req);
          return unresolved.length
            ? `Needs ${unresolved.join(', ')} — run whatever fills that first (often the Uploads folder).`
            : null;
        })();

    if (skipReason) {
      const status = head.querySelector('.run-status');
      status.textContent = 'skipped';
      status.className = 'run-status skip';
      row.append(el('div', 'hint skip-note', skipReason));
      skipped += 1;
      continue;
    }

    const ctx = await sendRequest(req);
    const ok = !ctx.networkError && ctx.status >= 200 && ctx.status < 300;
    const status = head.querySelector('.run-status');
    status.textContent = ctx.networkError ? 'network error' : `${ctx.status} · ${ctx.ms} ms`;
    status.className = `run-status ${ok ? 'ok' : 'fail'}`;

    if (!ok) {
      row.append(responseCard(ctx));
      failed = req.name;
      break;
    }
    if (ctx.captured.length) {
      const cap = el('div', 'captured');
      cap.append(el('span', 'cap-label', 'Captured'));
      for (const [k] of ctx.captured) cap.append(el('span', 'chip', k));
      row.append(cap);
    }
  }

  const tail = skipped ? ` (${skipped} skipped)` : '';
  pane.append(failed
    ? el('div', 'run-summary fail', `Stopped at “${failed}”.${tail}`)
    : el('div', 'run-summary ok', `All ${requests.length - skipped} requests passed.${tail}`));
}

// ── variables panel ────────────────────────────────────────────────────────
function renderVars() {
  const host = $('#var-list');
  const focused = document.activeElement;
  const focusedKey = focused?.dataset?.varKey;
  host.textContent = '';

  for (const key of Object.keys(state.env)) {
    if (key === 'base_url') continue; // lives in the top bar
    const row = el('label', 'var-row');
    row.append(el('span', 'vk', key));
    const input = el('input');
    input.type = 'text';
    input.value = state.env[key];
    input.spellcheck = false;
    input.dataset.varKey = key;
    input.placeholder = 'unset';
    input.classList.toggle('empty', !state.env[key]);
    input.oninput = () => {
      state.env[key] = input.value;
      persistEnv();
      if (state.item) renderUrlLine();
      renderAuthState();
    };
    row.append(input);
    host.append(row);
  }
  if (focusedKey) host.querySelector(`[data-var-key="${CSS.escape(focusedKey)}"]`)?.focus();
}

function renderAuthState() {
  const signedIn = Boolean(state.env.access_token);
  $('#auth-dot').className = `dot ${signedIn ? 'on' : ''}`;
  $('#auth-label').textContent = signedIn ? 'signed in' : 'not signed in';
}

/** Just enough markdown for the generated descriptions: `code`, **bold**, links. */
function mdLite(text) {
  const esc = text.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
  return esc
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br>');
}

// ── boot ───────────────────────────────────────────────────────────────────
async function boot() {
  const spec = await fetch('spec.json').then((r) => r.json());
  state.collection = spec.collection;
  state.seedEnv = Object.fromEntries(spec.environment.values.map((v) => [v.key, v.value]));

  // Served from the API itself, so default to this origin rather than the seed's
  // localhost:3000 — that makes the playground work unchanged on staging.
  state.seedEnv.base_url = `${location.origin}/api/${state.seedEnv.api_version || 'v1'}`;

  let stored = {};
  try { stored = JSON.parse(localStorage.getItem(STORE_KEY) || '{}'); } catch { /* ignore */ }
  state.env = { ...state.seedEnv, ...stored };

  $('#base-url').value = state.env.base_url;
  $('#base-url').oninput = (e) => {
    state.env.base_url = e.target.value;
    persistEnv();
    if (state.item) renderUrlLine();
  };

  $('#filter').oninput = (e) => renderTree(e.target.value);
  $('#send').onclick = async () => {
    const btn = $('#send');
    btn.disabled = true;
    btn.textContent = 'Sending…';
    const ctx = await sendRequest(state.item);
    const host = $('#response');
    host.textContent = '';
    host.append(responseCard(ctx));
    renderUrlLine();
    btn.disabled = false;
    btn.textContent = 'Send';
  };
  $('#body-editor').oninput = (e) => { editsFor(state.item).body = e.target.value; };
  for (const btn of $('#req-tabs').children) btn.onclick = () => selectTab(btn.dataset.tab);
  $('#reset-vars').onclick = () => {
    state.env = { ...state.seedEnv, base_url: state.env.base_url };
    persistEnv();
    renderVars();
    renderAuthState();
    if (state.item) renderUrlLine();
  };

  renderTree();
  renderVars();
  renderAuthState();
}

boot().catch((err) => {
  document.body.innerHTML = `<div style="padding:2rem;font:14px system-ui">
    <h2>Could not load spec.json</h2>
    <p>${err.message}</p>
    <p>Regenerate it with <code>node postman/generate.js</code>.</p>
  </div>`;
});
